[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.backend"
watchPatterns = ["backend/**/*.go"]

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"
healthcheckTimeout = 100
startCommand = "./dtech-api"
